### ISSUE TITLE
The chosen words are usually very strange/unknown

### ISSUE THREAD

**Issue by josinger** [fireph/quordle-es#1]
It's great that there is a Spanish version of this game, but right now it's unplayable because the words to guess are extremely rare. Perhaps you should consider using another word list that only contains commonly used words.

**Comment by fireph** [comment]
The word list has been improved, try it out and let me know what you think!

**Comment by eliblanco87** [comment]
They are still really strange words, for example today: SARZA, JIMAR, LICUA, CHAZO. Three of those I never heard or read.
Being a spanish speaker, I find the English Quordle easier than the Spanish one
